DROP TABLE IF EXISTS file CASCADE;
CREATE TABLE file (
	id BIGSERIAL PRIMARY KEY,
	page_id BIGINT NOT NULL,
	type VARCHAR NOT NULL,
	orig_name VARCHAR NOT NULL
);

ALTER TABLE file ADD FOREIGN KEY (page_id) REFERENCES public.page(id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
CREATE INDEX "file_page_id" ON file(page_id);
